# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4a6d81b75b3846ea63ce06d4969a97b526ff9d532c2f31fc6f08a3c3ac5e5a1e73523c862159558ca1c2d701701d064d9e46a469c13dff960e0d7b7fea7ebcc

test:
  secret_key_base: 87a8974bce17e1ad4d7e2221b3d3c36487627609f9c0e4e5a2cc9803034946f0327ad3c03e22a4904c121bb39570e72710330944370df3cffd5ad27d5d3a5684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
